/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pagereplacement;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.SwingConstants;
import java.awt.Font;
import javax.swing.JTextArea;
import javax.swing.ScrollPaneConstants;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.Cursor;

/**
 *
 * @author dell
 */
public class LifoInfo extends javax.swing.JFrame {

    /**
     * Creates new form Lock_Var_Info
     */
    public LifoInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane1.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setMaximumSize(new Dimension(1000, 400));
        jScrollPane1.setPreferredSize(new Dimension(1000, 400));
        jScrollPane1.setBounds(0, 80, 1008, 455);
        jScrollPane1.setMinimumSize(new Dimension(1000, 400));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1022, 572));
        setPreferredSize(new java.awt.Dimension(1022, 572));
        
        txtrLockVariable = new JTextArea();
        txtrLockVariable.setEditable(false);
        txtrLockVariable.setCursor(Cursor.getPredefinedCursor(Cursor.MOVE_CURSOR));
        txtrLockVariable.setText("LIFO page Replacement:\r\n\r\n  \u2022\tLIFO stands for Last in First out, and it performs all activities like LIFO principle.\r\n  \u2022\tIn this algorithm, newest page is replaced which is arrived at last in to primary memory, and it uses the stack for monitoring all pages.\r\n  \u2022\tIt almost works as the FIFO algorithm but just it deletes the last page that enter in the stack that's why that page delete the first.\r\n\nNOTE:-Only frame is used for page replacement during entire procedure after all the frames get occupied.\r\n\nImplementation:\r\n\r\n\r \u2022\t It maintain a stack of all pages currently in main memory and remove the page that is at the top of stack the linked list.");
        txtrLockVariable.setWrapStyleWord(true);
        txtrLockVariable.setMinimumSize(new Dimension(4, 22));
        txtrLockVariable.setLineWrap(true);
        txtrLockVariable.setTabSize(1);
        txtrLockVariable.setFont(new Font("Verdana", Font.PLAIN, 18));
        txtrLockVariable.setBackground(new Color(192, 192, 192));
        jScrollPane1.setViewportView(txtrLockVariable);
        jPanel1.setLayout(null);
        
        btnNewButton = new JButton("Back");
        btnNewButton.setBackground(new Color(0, 128, 128));
        btnNewButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		index a = new index();
                a.setLocationRelativeTo(null);
                a.setVisible(true);
                dispose();
        	}
        });
        btnNewButton.setFont(new Font("Verdana", Font.PLAIN, 18));
        btnNewButton.setBounds(901, 495, 77, 30);
        jPanel1.add(btnNewButton);
        
        lblNewLabel = new JLabel("LAST IN FIRST OUT");
        lblNewLabel.setPreferredSize(new Dimension(1000, 81));
        lblNewLabel.setOpaque(true);
        lblNewLabel.setMinimumSize(new Dimension(1022, 81));
        lblNewLabel.setHorizontalAlignment(SwingConstants.CENTER);
        lblNewLabel.setForeground(new Color(230, 230, 250));
        lblNewLabel.setFont(new Font("Verdana", Font.BOLD, 40));
        lblNewLabel.setBackground(new Color(0, 128, 128));
        lblNewLabel.setBounds(0, 0, 1008, 81);
        jPanel1.add(lblNewLabel);
        jPanel1.add(jScrollPane1);
        GroupLayout groupLayout = new GroupLayout(getContentPane());
        groupLayout.setHorizontalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 1008, GroupLayout.PREFERRED_SIZE)
        );
        groupLayout.setVerticalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 535, GroupLayout.PREFERRED_SIZE)
        );
        getContentPane().setLayout(groupLayout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LruInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LruInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LruInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LruInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LifoInfo().setVisible(true);
            }
        });
    }
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private JTextArea txtrLockVariable;
    private JLabel lblNewLabel;
    private JButton btnNewButton;
}
