/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pagereplacement;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JLabel;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.SwingConstants;
import java.awt.Font;
import javax.swing.JTextField;
import javax.swing.JTextArea;
import javax.swing.UIManager;
import javax.swing.ScrollPaneConstants;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JScrollPane;
import java.awt.Cursor;

/**
 *
 * @author dell
 */
public class LruInfo extends javax.swing.JFrame {

    /**
     * Creates new form Lock_Var_Info
     */
    public LruInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane1.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setMaximumSize(new Dimension(1000, 400));
        jScrollPane1.setPreferredSize(new Dimension(1000, 400));
        jScrollPane1.setBounds(0, 80, 1008, 455);
        jScrollPane1.setMinimumSize(new Dimension(1000, 400));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1022, 572));
        setPreferredSize(new java.awt.Dimension(1022, 572));
        
        txtrLockVariable = new JTextArea();
        txtrLockVariable.setEditable(false);
        txtrLockVariable.setCursor(Cursor.getPredefinedCursor(Cursor.MOVE_CURSOR));
        txtrLockVariable.setText("LRU Page Replacement Algorithm:\r\n\r\n  \u2022\tAs the name suggests, this algorithm works on the principle of  \"Least Recently Used\".\r\n  \u2022\tIt replaces the page that has not been referred by the CPU for the longest time. \r\n  \u2022\tLeast Recently Used page replacement algorithm keeps track of page usage over a short period of time. It works on the idea that the pages that have been most heavily used in the past are most likely to be used heavily in the future too.\r\n  \u2022\tIn LRU, whenever page replacement happens, the page which has not been used for the longest amount of time is replaced.\r\n\t \r\nFor Example:\r\n  \u2022\tTotal number of references = 10\r\n  \u2022\tReference String: 4 , 7, 6, 1, 7, 6, 1, 2, 7, 2\r\n  \u2022\tTotal number of page faults occurred = 6\r\n\r\nAdvantages:\r\n1. Efficient.\r\n2. Doesn't suffer from Belady's Anomaly.\r\n\r\nDisadvantages:\r\n1. Complex Implementation.\r\n2. Expensive.\r\n3. Requires hardware support.\r\n");
        txtrLockVariable.setWrapStyleWord(true);
        txtrLockVariable.setMinimumSize(new Dimension(4, 22));
        txtrLockVariable.setLineWrap(true);
        txtrLockVariable.setTabSize(1);
        txtrLockVariable.setFont(new Font("Verdana", Font.PLAIN, 18));
        txtrLockVariable.setBackground(new Color(192, 192, 192));
        jScrollPane1.setViewportView(txtrLockVariable);
        jPanel1.setLayout(null);
        
        btnNewButton = new JButton("Back");
        btnNewButton.setBackground(new Color(0, 128, 128));
        btnNewButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		index a = new index();
                a.setLocationRelativeTo(null);
                a.setVisible(true);
                dispose();
        	}
        });
        btnNewButton.setFont(new Font("Verdana", Font.PLAIN, 18));
        btnNewButton.setBounds(901, 495, 77, 30);
        jPanel1.add(btnNewButton);
        
        lblNewLabel = new JLabel("LEAST RECENTLY USED");
        lblNewLabel.setPreferredSize(new Dimension(1000, 81));
        lblNewLabel.setOpaque(true);
        lblNewLabel.setMinimumSize(new Dimension(1022, 81));
        lblNewLabel.setHorizontalAlignment(SwingConstants.CENTER);
        lblNewLabel.setForeground(new Color(230, 230, 250));
        lblNewLabel.setFont(new Font("Verdana", Font.BOLD, 40));
        lblNewLabel.setBackground(new Color(0, 128, 128));
        lblNewLabel.setBounds(0, 0, 1008, 81);
        jPanel1.add(lblNewLabel);
        jPanel1.add(jScrollPane1);
        GroupLayout groupLayout = new GroupLayout(getContentPane());
        groupLayout.setHorizontalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 1008, GroupLayout.PREFERRED_SIZE)
        );
        groupLayout.setVerticalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 535, GroupLayout.PREFERRED_SIZE)
        );
        getContentPane().setLayout(groupLayout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LruInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LruInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LruInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LruInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LruInfo().setVisible(true);
            }
        });
    }
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private JTextArea txtrLockVariable;
    private JLabel lblNewLabel;
    private JButton btnNewButton;
}
