/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home;
import diskscheduling.Menu;
import javafx.application.Application;
import concurrency.Index;
import pagereplacement.index;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.GroupLayout;
import javax.swing.JPanel;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import javax.swing.border.LineBorder;
import javax.swing.border.MatteBorder;

import com.sun.tools.javac.Main;

import javax.swing.UIManager;
import java.awt.SystemColor;
import javax.swing.JLabel;


public class Home extends javax.swing.JFrame {

    public class About_Us {

	}
	/**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel1.setBounds(0, 0, 1017, 81);
        btnDiskSch = new javax.swing.JButton();
        btnDiskSch.setForeground(Color.BLACK);
        btnDiskSch.setBackground(new Color(0,150,136));
        btnDiskSch.setBounds(346, 173, 309, 36);
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator1.setBounds(356, 215, 289, 2);
        btnConcur = new javax.swing.JButton();
        btnConcur.setBackground(new Color(0,150,136));
        btnConcur.setBounds(346, 221, 309, 36);
        btnSch = new javax.swing.JButton();
        btnSch.setBounds(346, 322, 309, 36);
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator2.setBounds(356, 314, 289, 2);
        btnPageRep = new javax.swing.JButton();
        btnPageRep.setBounds(346, 271, 309, 36);
        btnPageRep.setBackground(new Color(0,150,136));
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator4.setBounds(356, 263, 289, 2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1022, 572));
        setPreferredSize(new java.awt.Dimension(1022, 572));
        setResizable(false);

        jPanel1.setBackground(UIManager.getColor("ComboBox.buttonShadow"));
        jPanel1.setMinimumSize(new java.awt.Dimension(1022, 572));

        jLabel1.setBackground(new Color(0, 128, 128));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel1.setForeground(new Color(230, 230, 250));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setLabelFor(jPanel1);
        jLabel1.setText("Operating System Virtual Lab");
        jLabel1.setOpaque(true);

        btnDiskSch.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        btnDiskSch.setText("Disk Scheduling");
        btnDiskSch.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDiskSch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDiskSch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiskSchActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setMinimumSize(new java.awt.Dimension(50, 2));
        jSeparator1.setOpaque(true);
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 2));

        btnConcur.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        btnConcur.setText("Concurrency And Deadlock");
        btnConcur.setFocusPainted(false);
        btnConcur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcurActionPerformed(evt);
            }
        });

        btnSch.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        btnSch.setText("Scheduling Algorithms");
        btnSch.setBackground(new Color(0,150,136));
        btnSch.setFocusCycleRoot(true);
        btnSch.setFocusPainted(false);
        btnSch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSchActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setOpaque(true);

        btnPageRep.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        btnPageRep.setText("Page Replacement Algorithms");
        btnPageRep.setFocusCycleRoot(true);
        btnPageRep.setFocusPainted(false);
        btnPageRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPageRepActionPerformed(evt);
            }
        });

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(1)
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 1017, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 543, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(19, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);
        jPanel1.setLayout(null);
        jPanel1.add(jLabel1);
        jPanel1.add(btnDiskSch);
        jPanel1.add(jSeparator1);
        jPanel1.add(btnConcur);
        jPanel1.add(jSeparator4);
        jPanel1.add(btnPageRep);
        jPanel1.add(jSeparator2);
        jPanel1.add(btnSch);
        
        JLabel lblNewLabel = new JLabel("");
        lblNewLabel.setIcon(new ImageIcon("C:\\Users\\jmrpa\\eclipse-workspace\\Trial\\src\\home\\1.png"));
        lblNewLabel.setBounds(0, 0, 1098, 543);
        jPanel1.add(lblNewLabel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDiskSchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiskSchActionPerformed
 
        Menu a = new Menu();
        a.setLocationRelativeTo(null);
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDiskSchActionPerformed

    private void btnConcurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcurActionPerformed
        // TODO add your handling code here:
    	dispose();
    	Application.launch(concurrency.Main.class);
    }//GEN-LAST:event_btnConcurActionPerformed

    private void btnSchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSchActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(new Home(), "This module hasn't been added yet!!");
    }//GEN-LAST:event_btnSchActionPerformed

    private void btnPageRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPageRepActionPerformed
        // TODO add your handling code here:
        index a = new index();
        a.setLocationRelativeTo(null);
        a.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnPageRepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    	
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Home a = new Home();
                a.setSize(1022, 572);
                a.setLocationRelativeTo(null);
                a.setVisible(true);
            }
        });
    }
    private javax.swing.JButton btnConcur;
    private javax.swing.JButton btnDiskSch;
    private javax.swing.JButton btnPageRep;
    private javax.swing.JButton btnSch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    /**
     * @wbp.nonvisual location=103,-16
     */
    private final JPanel panel = new JPanel();
}
